<?xml version="1.0" encoding="ISO-8859-1"?>
<!--
 ! Excerpted from "Mastering Dojo",
 ! published by The Pragmatic Bookshelf.
 ! Copyrights apply to this code. It may not be used to create training material, 
 ! courses, books, articles, and the like. Contact us if you are in doubt.
 ! We make no guarantees that this code is fit for any purpose. 
 ! Visit http://www.pragmaticprogrammer.com/titles/rgdojo for more book information.
-->
<!DOCTYPE genetox [
<!ENTITY auml  "&#228;">
<!ENTITY ouml  "&#246;">
<!ENTITY uuml  "&#252;">
<!ELEMENT genetox (DOC)+>
<!ELEMENT DOC ((DOCNO|NameOfSubstance|CASRegistryNumber|DateRevised|
acta|actb|asca|
ascb|asta|astb|
ccat|date|dosra|
dosrb|gtn|refa|
refb|resa|resb|
rpta|rptb|sexa|
sexb|spcta|spctb|
sy|tax)*)>
<!ELEMENT gena ((spcta|sexa|asta|asca|resa|acta|dosra|rpta|refa)*)>
<!ELEMENT genb ((spctb|sexb|astb|ascb|resb|actb|dosrb|rptb|refb)*)>
<!ELEMENT DOCNO (#PCDATA)>
<!ELEMENT NameOfSubstance (#PCDATA)>
<!ELEMENT CASRegistryNumber (#PCDATA)>
<!ELEMENT DateRevised (#PCDATA)>
<!ELEMENT acta (#PCDATA)>
<!ELEMENT actb (#PCDATA)>
<!ELEMENT asca (#PCDATA)>
<!ELEMENT ascb (#PCDATA)>
<!ELEMENT asta (#PCDATA)>
<!ELEMENT astb (#PCDATA)>
<!ELEMENT ccat (#PCDATA)>
<!ELEMENT date (#PCDATA)>
<!ELEMENT dosra (#PCDATA)>
<!ELEMENT dosrb (#PCDATA)>
<!ELEMENT gtn (#PCDATA)>
<!ELEMENT refa (#PCDATA)>
<!ELEMENT refb (#PCDATA)>
<!ELEMENT resa (#PCDATA)>
<!ELEMENT resb (#PCDATA)>
<!ELEMENT rpta (#PCDATA)>
<!ELEMENT rptb (#PCDATA)>
<!ELEMENT sexa (#PCDATA)>
<!ELEMENT sexb (#PCDATA)>
<!ELEMENT spcta (#PCDATA)>
<!ELEMENT spctb (#PCDATA)>
<!ELEMENT sy (#PCDATA)>
<!ELEMENT tax (#PCDATA)>
]>

<genetox>
    <DOC>
        <DOCNO>1</DOCNO>
        <date>19920531</date>
        <DateRevised>
            Field Update on 05/31/1992, 
            2 fields added/edited/deleted.
        </DateRevised>
        <DateRevised>
            Complete update on 01/30/1991, 
            4 fields added/edited/deleted.
        </DateRevised>
        <NameOfSubstance>IRRADIATED POTATO EXTRACT</NameOfSubstance>
        <CASRegistryNumber>NO CAS RN</CASRegistryNumber>
        <ccat>
            Heterocyclic rings not otherwise classified, 
            unclassified compounds
        </ccat>
        <tax>In vivo mammalian somatic cells - chromosome effects</tax>
        <gena>
            <spcta>Mammalian polychromatic erythrocytes</spcta>
            <asta>Micronucleus test, chromosome aberrations</asta>
            <asca>MNTT</asca>
            <resa>No conclusion</resa>
            <rpta>EMICBACK/50890; MUTAT RES 123:61-118,1983</rpta>
        </gena>
        <gtn>$null$</gtn>
        <sy>$null$</sy>
        <spctb>$null$</spctb>
        <sexb>$null$</sexb>
        <astb>$null$</astb>
        <ascb>$null$</ascb>
        <resb>$null$</resb>
        <actb>$null$</actb>
        <dosrb>$null$</dosrb>
        <rptb>$null$</rptb>
        <refb>$null$</refb>
        <sexa>$null$</sexa>
        <acta>$null$</acta>
        <dosra>$null$</dosra>
        <refa>$null$</refa>
    </DOC>
    <DOC>
        <DOCNO>2</DOCNO>
        <date>19920531</date>
        <DateRevised>
            Field Update on 05/31/1992, 
            2 fields added/edited/deleted.
        </DateRevised>
        
        <DateRevised>Complete update on 01/30/1991, 4 fields added/edited/deleted.</DateRevised>
        <NameOfSubstance>IRRADIATED CHLOROGENIC ACID</NameOfSubstance>
        <CASRegistryNumber>NO CAS RN</CASRegistryNumber>
        <ccat>Heterocyclic rings not otherwise classified, unclassified compounds</ccat>
        <tax>In vivo mammalian somatic cells - chromosome effects</tax>
        <gena>
            <spcta>Mammalian polychromatic erythrocytes</spcta>
            <asta>Micronucleus test, chromosome aberrations</asta>
            <asca>MNTT</asca>
            <resa>No conclusion</resa>
            <rpta>EMICBACK/50890; MUTAT RES 123:61-118,1983</rpta>
        </gena>
        <gtn>$null$</gtn>
        <sy>$null$</sy>
        <spctb>$null$</spctb>
        <sexb>$null$</sexb>
        <astb>$null$</astb>
        <ascb>$null$</ascb>
        <resb>$null$</resb>
        <actb>$null$</actb>
        <dosrb>$null$</dosrb>
        <rptb>$null$</rptb>
        <refb>$null$</refb>
        <sexa>$null$</sexa>
        <acta>$null$</acta>
        <dosra>$null$</dosra>
        <refa>$null$</refa>
    </DOC>
    <DOC>
        <DOCNO>3</DOCNO>
        <date>19920531</date>
        <DateRevised>Field Update on 05/31/1992, 2 fields added/edited/deleted.</DateRevised>
        <DateRevised>Field Update on 08/22/1991, 1 field added/edited/deleted.</DateRevised>
        <DateRevised>Complete update on 01/30/1991, 4 fields added/edited/deleted.</DateRevised>
        <NameOfSubstance>WHOLE SMOKE CONDENSATE</NameOfSubstance>
        <CASRegistryNumber>NO CAS RN</CASRegistryNumber>
        <ccat>Heterocyclic rings not otherwise classified, unclassified compounds</ccat>
        <tax>In vitro mammalian - gene mutation</tax>
        <gena>
            <spcta>Mouse lymphoma (L5178Y) cells</spcta>
            <asta>Forward gene mutation at the thymidine kinase (TK) locus; chromosome aberrations</asta>
            <asca>L51+*</asca>
            <resa>Positive</resa>
            <acta>With metabolic activation</acta>
            <rpta>EMICBACK/50691; MUTAT RES 115:225-251,1983</rpta>
            <refa>EMICBACK/31144; MUTAT RES 59:61-108,1979</refa>
        </gena>
        <gtn>$null$</gtn>
        <sy>$null$</sy>
        <spctb>$null$</spctb>
        <sexb>$null$</sexb>
        <astb>$null$</astb>
        <ascb>$null$</ascb>
        <resb>$null$</resb>
        <actb>$null$</actb>
        <dosrb>$null$</dosrb>
        <rptb>$null$</rptb>
        <refb>$null$</refb>
        <sexa>$null$</sexa>
        <dosra>$null$</dosra>
    </DOC>
    <DOC>
        <DOCNO>4</DOCNO>
        <date>19920615</date>
        <DateRevised>Field Update on 06/15/1992, 2 fields added/edited/deleted.</DateRevised>
        <DateRevised>Field Update on 05/31/1992, 1 field added/edited/deleted.</DateRevised>
        <DateRevised>Field Update on 08/22/1991, 1 field added/edited/deleted.</DateRevised>
        <DateRevised>Complete update on 01/30/1991, 4 fields added/edited/deleted.</DateRevised>
        <NameOfSubstance>COAL LIQUID A-3</NameOfSubstance>
        <CASRegistryNumber>NO CAS RN</CASRegistryNumber>
        <ccat>Heterocyclic rings not otherwise classified, unclassified compounds</ccat>
        <tax>In vivo mammalian somatic cells - gene mutation</tax>
        <tax>In vivo mammalian germ cells - gene mutation</tax>
        <gena>
            <spcta>Mouse</spcta>
            <sexa>Female</sexa>
            <asta>Spot test, gene mutation</asta>
            <asca>MST-</asca>
            <resa>Negative</resa>
            <rpta>EMICBACK/41536; MUTAT RES 86:355-379,1981</rpta>
            <refa>EMICBACK/31729; REPORT EPA REPORT,18PP,1978</refa>
        </gena>
        <gena>
            <spcta>Mouse</spcta>
            <sexa>Male</sexa>
            <asta>Specific locus test, gene mutation</asta>
            <asca>SLT+</asca>
            <resa>Positive</resa>
            <rpta>EMICBACK/41535; MUTAT RES 86:329-354,1981</rpta>
            <refa>EMICBACK/31729; REPORT EPA REPORT,18PP,1978</refa>
        </gena>
        <gtn>$null$</gtn>
        <sy>$null$</sy>
        <spctb>$null$</spctb>
        <sexb>$null$</sexb>
        <astb>$null$</astb>
        <ascb>$null$</ascb>
        <resb>$null$</resb>
        <actb>$null$</actb>
        <dosrb>$null$</dosrb>
        <rptb>$null$</rptb>
        <refb>$null$</refb>
        <acta>$null$</acta>
        <dosra>$null$</dosra>
    </DOC>
    <DOC>
        <DOCNO>5</DOCNO>
        <date>19920531</date>
        <DateRevised>Field Update on 05/31/1992, 2 fields added/edited/deleted.</DateRevised>
        <DateRevised>Complete update on 01/30/1991, 4 fields added/edited/deleted.</DateRevised>
        <NameOfSubstance>LEAD SMELTING</NameOfSubstance>
        <CASRegistryNumber>NO CAS RN</CASRegistryNumber>
        <ccat>Heterocyclic rings not otherwise classified, unclassified compounds</ccat>
        <tax>Plants - gene mutation</tax>
        <gena>
            <spcta>Zea mays (corn)</spcta>
            <asta>Gene mutation</asta>
            <asca>ZEM+</asca>
            <resa>Positive</resa>
            <rpta>EMICBACK/48096; MUTAT RES 99:317-337,1982</rpta>
        </gena>
        <gtn>$null$</gtn>
        <sy>$null$</sy>
        <spctb>$null$</spctb>
        <sexb>$null$</sexb>
        <astb>$null$</astb>
        <ascb>$null$</ascb>
        <resb>$null$</resb>
        <actb>$null$</actb>
        <dosrb>$null$</dosrb>
        <rptb>$null$</rptb>
        <refb>$null$</refb>
        <sexa>$null$</sexa>
        <acta>$null$</acta>
        <dosra>$null$</dosra>
        <refa>$null$</refa>
    </DOC>
    <DOC>
        <DOCNO>6</DOCNO>
        <date>19910822</date>
        <DateRevised>Complete update on 01/30/1991, 5 fields added/edited/deleted.</DateRevised>
        <NameOfSubstance>RETRONECINE-7,9-PIPERONYLATE</NameOfSubstance>
        <CASRegistryNumber>39818-13-8</CASRegistryNumber>
        <ccat>Alkaloids</ccat>
        <tax>Plants - chromosome effects</tax>
        <gena>
            <spcta>Allium cepa</spcta>
            <asta>Chromosome aberrations</asta>
            <asca>ALC+</asca>
            <resa>Positive</resa>
            <rpta>EMICBACK/48093; MUTAT RES 99:273-291,1982</rpta>
        </gena>
        <gtn>$null$</gtn>
        <sy>$null$</sy>
        <spctb>$null$</spctb>
        <sexb>$null$</sexb>
        <astb>$null$</astb>
        <ascb>$null$</ascb>
        <resb>$null$</resb>
        <actb>$null$</actb>
        <dosrb>$null$</dosrb>
        <rptb>$null$</rptb>
        <refb>$null$</refb>
        <sexa>$null$</sexa>
        <acta>$null$</acta>
        <dosra>$null$</dosra>
        <refa>$null$</refa>
    </DOC>
    <DOC>
        <DOCNO>7</DOCNO>
        <date>19920531</date>
        <DateRevised>Field Update on 05/31/1992, 2 fields added/edited/deleted.</DateRevised>
        <DateRevised>Complete update on 01/30/1991, 4 fields added/edited/deleted.</DateRevised>
        <NameOfSubstance>SLUDGE FROM PAPER RECYCLING PLANT</NameOfSubstance>
        <CASRegistryNumber>NO CAS RN</CASRegistryNumber>
        <ccat>Heterocyclic rings not otherwise classified, unclassified compounds</ccat>
        <tax>Plants - gene mutation</tax>
        <gena>
            <spcta>Glycine max (soybean)</spcta>
            <asta>Gene mutation</asta>
            <asca>GLM+</asca>
            <resa>Positive</resa>
            <rpta>EMICBACK/48097; MUTAT RES 99:339-347,1982</rpta>
        </gena>
        <gtn>$null$</gtn>
        <sy>$null$</sy>
        <spctb>$null$</spctb>
        <sexb>$null$</sexb>
        <astb>$null$</astb>
        <ascb>$null$</ascb>
        <resb>$null$</resb>
        <actb>$null$</actb>
        <dosrb>$null$</dosrb>
        <rptb>$null$</rptb>
        <refb>$null$</refb>
        <sexa>$null$</sexa>
        <acta>$null$</acta>
        <dosra>$null$</dosra>
        <refa>$null$</refa>
    </DOC>
    <DOC>
        <DOCNO>8</DOCNO>
        <date>19920531</date>
        <DateRevised>Field Update on 05/31/1992, 2 fields added/edited/deleted.</DateRevised>
        <DateRevised>Complete update on 01/30/1991, 4 fields added/edited/deleted.</DateRevised>
        <NameOfSubstance>NITROSATION PRODUCTS OF METHYLGUANIDINE</NameOfSubstance>
        <CASRegistryNumber>NO CAS RN</CASRegistryNumber>
        <ccat>Nitrosamides, nitrosoureas, nitrosoguanidines</ccat>
        <tax>In vitro mammalian - chromosome effects</tax>
        <gena>
            <spcta>Human cell culture</spcta>
            <asta>Chromosome aberrations in vitro</asta>
            <asca>CYZ+</asca>
            <resa>Positive</resa>
            <rpta>EMICBACK/41729; MUTAT RES 87:143-188,1981</rpta>
        </gena>
        <gtn>$null$</gtn>
        <sy>$null$</sy>
        <spctb>$null$</spctb>
        <sexb>$null$</sexb>
        <astb>$null$</astb>
        <ascb>$null$</ascb>
        <resb>$null$</resb>
        <actb>$null$</actb>
        <dosrb>$null$</dosrb>
        <rptb>$null$</rptb>
        <refb>$null$</refb>
        <sexa>$null$</sexa>
        <acta>$null$</acta>
        <dosra>$null$</dosra>
        <refa>$null$</refa>
    </DOC>
    <DOC>
        <DOCNO>9</DOCNO>
        <date>19910130</date>
        <DateRevised>Complete update on 01/30/1991, 5 fields added/edited/deleted.</DateRevised>
        <NameOfSubstance>HAIR DYE MAHOGANY</NameOfSubstance>
        <CASRegistryNumber>NO CAS RN</CASRegistryNumber>
        <tax>Lower eukaryotes - other genotoxic effects</tax>
        <gena>
            <spcta>Saccharomyces cerevisiae</spcta>
            <asta>Mitotic recombination or gene conversion</asta>
            <asca>YEC+</asca>
            <resa>Positive</resa>
            <rpta>EMICBACK/52546; MUTAT RES 133:199-244,1984</rpta>
        </gena>
        <gtn>$null$</gtn>
        <sy>$null$</sy>
        <ccat>$null$</ccat>
        <spctb>$null$</spctb>
        <sexb>$null$</sexb>
        <astb>$null$</astb>
        <ascb>$null$</ascb>
        <resb>$null$</resb>
        <actb>$null$</actb>
        <dosrb>$null$</dosrb>
        <rptb>$null$</rptb>
        <refb>$null$</refb>
        <sexa>$null$</sexa>
        <acta>$null$</acta>
        <dosra>$null$</dosra>
        <refa>$null$</refa>
    </DOC>
    <DOC>
        <DOCNO>10</DOCNO>
        <date>19920531</date>
        <DateRevised>Field Update on 05/31/1992, 2 fields added/edited/deleted.</DateRevised>
        <DateRevised>Complete update on 01/30/1991, 4 fields added/edited/deleted.</DateRevised>
        <NameOfSubstance>B. THURINGIENSIS (CRUDE) EXOTOXIN</NameOfSubstance>
        <CASRegistryNumber>NO CAS RN</CASRegistryNumber>
        <ccat>Heterocyclic rings not otherwise classified, unclassified compounds</ccat>
        <tax>Insects - gene mutation</tax>
        <tax>Lower eukaryotes - other genotoxic effects</tax>
        <gena>
            <spcta>Drosophila melanogaster</spcta>
            <asta>Sex-linked recessive lethal gene mutation</asta>
            <asca>SRLT</asca>
            <resa>No conclusion</resa>
            <rpta>EMICBACK/50912; MUTAT RES 123:183-279,1983</rpta>
        </gena>
        <gena>
            <spcta>Saccharomyces cerevisiae</spcta>
            <asta>Mitotic recombination or gene conversion</asta>
            <asca>YEC-</asca>
            <resa>Negative</resa>
            <rpta>EMICBACK/52546; MUTAT RES 133:199-244,1984</rpta>
        </gena>
        <gena>
            <spcta>Saccharomyces cerevisiae</spcta>
            <asta>Mitotic recombination or gene conversion</asta>
            <asca>YEH-</asca>
            <resa>Negative</resa>
            <rpta>EMICBACK/52546; MUTAT RES 133:199-244,1984</rpta>
        </gena>
        <gtn>$null$</gtn>
        <sy>$null$</sy>
        <spctb>$null$</spctb>
        <sexb>$null$</sexb>
        <astb>$null$</astb>
        <ascb>$null$</ascb>
        <resb>$null$</resb>
        <actb>$null$</actb>
        <dosrb>$null$</dosrb>
        <rptb>$null$</rptb>
        <refb>$null$</refb>
        <sexa>$null$</sexa>
        <acta>$null$</acta>
        <dosra>$null$</dosra>
        <refa>$null$</refa>
    </DOC>
    <DOC>
        <DOCNO>11</DOCNO>
        <date>19920531</date>
        <DateRevised>Field Update on 05/31/1992, 2 fields added/edited/deleted.</DateRevised>
        <DateRevised>Complete update on 01/30/1991, 4 fields added/edited/deleted.</DateRevised>
        <NameOfSubstance>CIGARETTE SMOKE EXTRACTS</NameOfSubstance>
        <CASRegistryNumber>NO CAS RN</CASRegistryNumber>
        <ccat>Heterocyclic rings not otherwise classified, unclassified compounds</ccat>
        <tax>Lower eukaryotes - other genotoxic effects</tax>
        <gena>
            <spcta>Saccharomyces cerevisiae</spcta>
            <asta>Mitotic recombination or gene conversion</asta>
            <asca>YEH+</asca>
            <resa>Positive</resa>
            <rpta>EMICBACK/52546; MUTAT RES 133:199-244,1984</rpta>
        </gena>
        <gtn>$null$</gtn>
        <sy>$null$</sy>
        <spctb>$null$</spctb>
        <sexb>$null$</sexb>
        <astb>$null$</astb>
        <ascb>$null$</ascb>
        <resb>$null$</resb>
        <actb>$null$</actb>
        <dosrb>$null$</dosrb>
        <rptb>$null$</rptb>
        <refb>$null$</refb>
        <sexa>$null$</sexa>
        <acta>$null$</acta>
        <dosra>$null$</dosra>
        <refa>$null$</refa>
    </DOC>
    <DOC>
        <DOCNO>14</DOCNO>
        <date>19980322</date>
        <DateRevised>Field Update on 03/22/1998, 1 field added/edited/deleted.</DateRevised>
        <DateRevised>Field Update on 03/22/1998, 1 field added/edited/deleted.</DateRevised>
        <DateRevised>Field Update on 03/22/1998, 1 field added/edited/deleted.</DateRevised>
        <DateRevised>Field Update on 03/22/1998, 1 field added/edited/deleted.</DateRevised>
        <DateRevised>Field Update on 05/31/1992, 1 field added/edited/deleted.</DateRevised>
        <DateRevised>Complete update on 01/30/1991, 5 fields added/edited/deleted.</DateRevised>
        <NameOfSubstance>FORMALDEHYDE</NameOfSubstance>
        <CASRegistryNumber>50-00-0</CASRegistryNumber>
        <ccat>Aldehydes, anhydrides</ccat>
        <tax>Lower eukaryotes - gene mutation</tax>
        <tax>Insects - gene mutation</tax>
        <tax>In vitro mammalian - gene mutation</tax>
        <tax>Insects - chromosome effects</tax>
        <tax>In vivo mammalian somatic cells - chromosome effects</tax>
        <tax>Prokaryotes - other genotoxic effects</tax>
        <tax>Lower eukaryotes - other genotoxic effects</tax>
        <tax>In vitro mammalian, UDS - other genotoxic effects</tax>
        <genb>
            <spctb>Mammalian polychromatic erythrocytes</spctb>
            <astb>Micronucleus test, chromosome aberrations</astb>
            <ascb>MNTT</ascb>
            <resb>No conclusion</resb>
            <rptb>EMICBACK/77345; MUTAT RES 239:29-80,1990</rptb>
            <refb>EMICBACK/41641; MUTAT RES 90:91-109,1981</refb>
        </genb>
        <genb>
            <spctb>Chinese hamster ovary (CHO) cells</spctb>
            <astb>Forward gene mutation at the HPRT locus</astb>
            <ascb>CHOT</ascb>
            <resb>No conclusion</resb>
            <rptb>EMICBACK/71517; MUTAT RES 196:17-36,1988</rptb>
            <refb>EMICBACK/53976; J TOXICOL ENVIRON HEALTH 12:27-38,1983</refb>
        </genb>
        <genb>
            <spctb>Human</spctb>
            <astb>Sister-chromatid exchange (SCE) in vitro</astb>
            <ascb>SC1+D</ascb>
            <resb>Positive</resb>
            <dosrb>With dose response</dosrb>
            <rptb>EMIC/91392; Mutat Res 1993 Sep;297(2):101-80</rptb>
            <refb>EMICBACK/36488; DRUG ALCOHOL DEPEND 4:91-94,1979</refb>
        </genb>
        <genb>
            <spctb>Human lymphocytes</spctb>
            <astb>Sister-chromatid exchange (SCE) in vitro</astb>
            <ascb>SCL+D</ascb>
            <resb>Positive</resb>
            <dosrb>With dose response</dosrb>
            <rptb>EMIC/91392; Mutat Res 1993 Sep;297(2):101-80</rptb>
            <refb>EMICBACK/36488; DRUG ALCOHOL DEPEND 4:91-94,1979</refb>
        </genb>
        <genb>
            <spctb>Nonhuman</spctb>
            <astb>Sister-chromatid exchange (SCE) in vitro</astb>
            <ascb>SC2+D</ascb>
            <resb>Positive</resb>
            <dosrb>With dose response</dosrb>
            <rptb>EMIC/91392; Mutat Res 297:101-180,1993</rptb>
            <refb>EMICBACK/52148; MUTAT RES 122:355-360,1983</refb>
        </genb>
        <genb>
            <spctb>Human lymphocytes</spctb>
            <astb>Sister-chromatid exchange (SCE) in vivo</astb>
            <ascb>SCY+</ascb>
            <resb>Positive</resb>
            <rptb>EMIC/91392; Mutat Res 1993 Sep;297(2):101-80</rptb>
            <refb>EMICBACK/58397; MUTAT RES 141:89-93,1984</refb>
        </genb>
        <gena>
            <spcta>Neurospora crassa</spcta>
            <asta>Reverse gene mutation</asta>
            <asca>NER+</asca>
            <resa>Positive</resa>
            <rpta>EMICBACK/52327; MUTAT RES 133:87-134,1984</rpta>
        </gena>
        <gena>
            <spcta>Escherichia coli polA (W3119 vs P3478)</spcta>
            <asta>Rec-assay, DNA effects (bacterial DNA repair)</asta>
            <asca>RE1+</asca>
            <resa>Positive</resa>
            <rpta>EMICBACK/45048; MUTAT RES 87:211-297,1981</rpta>
        </gena>
        <gena>
            <spcta>Drosophila melanogaster</spcta>
            <asta>Sex-linked recessive lethal gene mutation</asta>
            <asca>SRL+</asca>
            <resa>Positive</resa>
            <rpta>EMICBACK/50912; MUTAT RES 123:183-279,1983</rpta>
        </gena>
        <gena>
            <spcta>Human diploid fibroblasts</spcta>
            <asta>Unscheduled DNA synthesis (UDS) in vitro, DNA effects</asta>
            <asca>UDHT</asca>
            <resa>No conclusion</resa>
            <rpta>EMICBACK/52100; MUTAT RES 123:363-410,1983</rpta>
        </gena>
        <gena>
            <spcta>Saccharomyces cerevisiae</spcta>
            <asta>Mitotic recombination or gene conversion</asta>
            <asca>YEC+</asca>
            <resa>Positive</resa>
            <rpta>EMICBACK/52546; MUTAT RES 133:199-244,1984</rpta>
        </gena>
        <gena>
            <spcta>Saccharomyces cerevisiae</spcta>
            <asta>Reverse gene mutation</asta>
            <asca>YER+</asca>
            <resa>Positive</resa>
            <rpta>EMICBACK/52546; MUTAT RES 133:199-244,1984</rpta>
        </gena>
        <gena>
            <spcta>Drosophila melanogaster</spcta>
            <sexa>Male</sexa>
            <asta>Heritable translocation test, chromosome aberrations</asta>
            <asca>DHT+</asca>
            <resa>Positive</resa>
            <rpta>EMICBACK/52867; MUTAT RES 134:61-88,1984</rpta>
        </gena>
        <gena>
            <spcta>Nonhuman</spcta>
            <asta>In vivo carcinogenicity studies</asta>
            <asca>CCG+</asca>
            <resa>Positive</resa>
            <rpta>EMICBACK/67174; MUTAT RES 185:1-195,1987</rpta>
        </gena>
        <gtn>$null$</gtn>
        <sy>$null$</sy>
        <sexb>$null$</sexb>
        <actb>$null$</actb>
        <acta>$null$</acta>
        <dosra>$null$</dosra>
        <refa>$null$</refa>
    </DOC>
    <DOC>
        <DOCNO>15</DOCNO>
        <date>19980322</date>
        <DateRevised>Field Update on 03/22/1998, 1 field added/edited/deleted.</DateRevised>
        <DateRevised>Complete update on 01/30/1991, 5 fields added/edited/deleted.</DateRevised>
        <NameOfSubstance>PHENOBARBITAL</NameOfSubstance>
        <CASRegistryNumber>50-06-6</CASRegistryNumber>
        <ccat>Carbamates, ureas, thioureas, dicarboximides</ccat>
        <ccat>Pyrimidine derivatives, purine derivatives</ccat>
        <tax>In vivo mammalian somatic cells - chromosome effects</tax>
        <tax>In vivo mammalian, sperm morphology - other genotoxic effects</tax>
        <tax>In vitro mammalian - cell transformation</tax>
        <genb>
            <spctb>Mammalian polychromatic erythrocytes</spctb>
            <astb>Micronucleus test, chromosome aberrations</astb>
            <ascb>MNT+</ascb>
            <resb>Positive</resb>
            <rptb>EMICBACK/77345; MUTAT RES 239:29-80,1990</rptb>
            <refb>EMICBACK/53701; IRCS MED SCI LIBR COMPEND 9:937-938,1981</refb>
        </genb>
        <genb>
            <spctb>Human lymphocytes</spctb>
            <astb>Sister-chromatid exchange (SCE) in vivo</astb>
            <ascb>SCY+</ascb>
            <resb>Positive</resb>
            <rptb>EMIC/91392; Mutat Res 1993 Sep;297(2):101-80</rptb>
            <refb>EMICBACK/58504; FOOD CHEM TOXICOL 22:1009-1012,1984</refb>
        </genb>
        <gena>
            <spcta>Syrian hamster embryo (SHE) cells</spcta>
            <asta>Cell transformation, clonal assay</asta>
            <asca>CTC-</asca>
            <resa>Negative</resa>
            <rpta>EMICBACK/50076; MUTAT RES 114:283-385,1983</rpta>
        </gena>
        <gena>
            <spcta>Mammalian polychromatic erythrocytes</spcta>
            <asta>Micronucleus test, chromosome aberrations</asta>
            <asca>MNTT</asca>
            <resa>No conclusion</resa>
            <rpta>EMICBACK/50890; MUTAT RES 123:61-118,1983</rpta>
        </gena>
        <gena>
            <spcta>Mouse</spcta>
            <sexa>Male</sexa>
            <asta>Sperm morphology</asta>
            <asca>SPI-</asca>
            <resa>Negative</resa>
            <rpta>EMICBACK/50126; MUTAT RES 115:1-72,1983</rpta>
        </gena>
        <gtn>$null$</gtn>
        <sy>$null$</sy>
        <sexb>$null$</sexb>
        <actb>$null$</actb>
        <dosrb>$null$</dosrb>
        <acta>$null$</acta>
        <dosra>$null$</dosra>
        <refa>$null$</refa>
    </DOC>
    <DOC>
        <DOCNO>16</DOCNO>
        <date>19980322</date>
        <DateRevised>Field Update on 03/22/1998, 1 field added/edited/deleted.</DateRevised>
        <DateRevised>Field Update on 04/06/1995, 1 field added/edited/deleted.</DateRevised>
        <DateRevised>Field Update on 06/15/1992, 1 field added/edited/deleted.</DateRevised>
        <DateRevised>Field Update on 08/30/1991, 1 field added/edited/deleted.</DateRevised>
        <DateRevised>Field Update on 08/22/1991, 1 field added/edited/deleted.</DateRevised>
        <DateRevised>Complete update on 01/30/1991, 5 fields added/edited/deleted.</DateRevised>
        <NameOfSubstance>MITOMYCIN C</NameOfSubstance>
        <CASRegistryNumber>50-07-7</CASRegistryNumber>
        <ccat>Anthraquinones, quinones</ccat>
        <ccat>Antibiotics, mycotoxins</ccat>
        <ccat>Aromatic amines, aliphatic amines, amides and sulfonamides</ccat>
        <ccat>Aziridines, nitrogen and sulfur mustards</ccat>
        <ccat>Carbamates, ureas, thioureas, dicarboximides</ccat>
        <tax>Prokaryotes - gene mutation</tax>
        <tax>Lower eukaryotes - gene mutation</tax>
        <tax>Plants - gene mutation</tax>
        <tax>Insects - gene mutation</tax>
        <tax>In vitro mammalian - gene mutation</tax>
        <tax>In vivo mammalian somatic cells - gene mutation</tax>
        <tax>In vivo mammalian germ cells - gene mutation</tax>
        <tax>Lower eukaryotes - chromosome effects</tax>
        <tax>Plants - chromosome effects</tax>
        <tax>In vitro mammalian - chromosome effects</tax>
        <tax>In vivo mammalian somatic cells - chromosome effects</tax>
        <tax>In vivo mammalian germ cells - chromosome effects</tax>
        <tax>Prokaryotes - other genotoxic effects</tax>
        <tax>Lower eukaryotes - other genotoxic effects</tax>
        <tax>In vitro mammalian, UDS - other genotoxic effects</tax>
        <tax>In vitro mammalian, SCE - other genotoxic effects</tax>
        <tax>In vivo mammalian, UDS - other genotoxic effects</tax>
        <tax>In vivo mammalian, SCE - other genotoxic effects</tax>
        <tax>In vivo mammalian, sperm morphology - other genotoxic effects</tax>
        <tax>In vivo mammalian, heritable sperm morphology - other genotoxic effects</tax>
        <genb>
            <spctb>Chinese hamster ovary (CHO) cells</spctb>
            <astb>Forward gene mutation at the HPRT locus</astb>
            <ascb>CHO+</ascb>
            <resb>Positive</resb>
            <rptb>EMICBACK/71517; MUTAT RES 196:17-36,1988</rptb>
            <refb>EMICBACK/45725; MUTAT RES 94:449-466,1982</refb>
        </genb>
        <genb>
            <spctb>Human lymphocytes</spctb>
            <astb>Sister-chromatid exchange (SCE) in vivo</astb>
            <ascb>SCY+</ascb>
            <resb>Positive</resb>
            <rptb>EMIC/91392; Mutat Res 1993 Sep;297(2):101-80</rptb>
            <refb>EMICBACK/35980; CANCER RES 40:477-480,1980</refb>
        </genb>
        <gena>
            <spcta>Nonhuman</spcta>
            <asta>Chromosome aberrations in vitro</asta>
            <asca>CY&amp;+</asca>
            <resa>Positive</resa>
            <rpta>EMICBACK/41729; MUTAT RES 87:143-188,1981</rpta>
        </gena>
        <gena>
            <spcta>Nonhuman bone marrow</spcta>
            <asta>Chromosome aberrations, in vivo</asta>
            <asca>CY#+</asca>
            <resa>Positive</resa>
            <rpta>EMICBACK/41729; MUTAT RES 87:143-188,1981</rpta>
        </gena>
        <gena>
            <spcta>Mammalian oocytes or early embryo</spcta>
            <asta>Chromosome aberrations in vivo</asta>
            <asca>CYO+</asca>
            <resa>Positive</resa>
            <rpta>EMICBACK/41729; MUTAT RES 87:143-188,1981</rpta>
        </gena>
        <gena>
            <spcta>Mammalian germ cells</spcta>
            <sexa>Male</sexa>
            <asta>Chromosome aberrations in vivo</asta>
            <asca>CY9+</asca>
            <resa>Positive</resa>
            <rpta>EMICBACK/41729; MUTAT RES 87:143-188,1981</rpta>
        </gena>
        <gena>
            <spcta>Rodents</spcta>
            <sexa>Male</sexa>
            <asta>Dominant lethal test</asta>
            <asca>DLT+</asca>
            <resa>Positive</resa>
            <rpta>EMICBACK/60142; MUTAT RES 154:49-67,1985</rpta>
        </gena>
        <gena>
            <spcta>Escherichia coli</spcta>
            <asta>Forward and reverse gene mutation, host-mediated assay</asta>
            <asca>HMB+</asca>
            <resa>Positive</resa>
            <rpta>EMICBACK/45734; MUTAT RES 98:319-374,1982</rpta>
            <refa>EMICBACK/28433; MUTAT RES 57:91-95,1978</refa>
        </gena>
        <gena>
            <spcta>Mouse</spcta>
            <sexa>Male</sexa>
            <asta>Heritable translocation test, chromosome aberrations</asta>
            <asca>HTT+</asca>
            <resa>Positive</resa>
            <rpta>EMICBACK/37491; MUTAT RES 76:191-215,1980</rpta>
            <refa>EMICBACK/28457; MUTAT RES 53:143-144,1978</refa>
        </gena>
        <gena>